stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  cache:
    key: npm-cache
    paths:
      - node_modules/

test:
  stage: test
  script:
    - npm test
  artifacts:
    paths:
      - coverage/

deploy:
  stage: deploy
  script:
    - npm run deploy
  only:
    - main
