stages:
  - build
  - test

build_image:
  stage: build
  script:
    - docker build -t my-app:latest .
    - docker tag my-app:latest my-registry/my-app:latest
  only:
    - main

test_image:
  stage: test
  script:
    - docker run --rm my-app:latest pytest tests/
  dependencies:
    - build_image
