stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building application..."
    - make build

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
    - make deploy
  when: manual
  only:
    - main
