stages:
  - test
  - staging
  - production

unit_tests:
  stage: test
  script:
    - npm test

staging_deploy:
  stage: staging
  script:
    - echo "Deploying to staging..."
    - make deploy-staging
  environment:
    name: staging
    url: https://staging.example.com

production_deploy:
  stage: production
  script:
    - echo "Deploying to production..."
    - make deploy-production
  environment:
    name: production
    url: https://www.example.com
  when: manual
  only:
    - main
